repos:
- repo: local
  hooks:
  - id: lint
    name: Lint
    language: golang
    entry: goimports -w api examples
    # files: '^api/.*\.go'
    # types: ["file", "go"]
    pass_filenames: false
    additional_dependencies:
      - golang.org/x/tools/cmd/goimports@v0.30.0
  - id: generate-doc
    name: Doc generation
    stages: [manual]
    language: golang
    entry: md-to-godoc
    files: 'README.md'
    pass_filenames: false
    additional_dependencies:
      - github.com/therve/md-to-godoc@452c0541b9500da3750489330b5a8f7a820a590c
  - id: docs
    name: Format documentation
    stages: [manual]
    language: node
    language_version: 20.5.0
    entry: prettier --write --list-different --ignore-unknown
    # "types": [text]
    files: 'README.md'
    pass_filenames: true
    additional_dependencies:
      # When updating the version of prettier, make sure to check the  pre-commit file
      # And keep the `entry` here up to date https://github.com/pre-commit/mirrors-prettier/blob/master/.pre-commit-hooks.yaml
      - prettier@3.0.0
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-case-conflict
