FROM golang:latest
ENTRYPOINT ["go"]
CMD ["test"]

COPY get-test-deps.sh /datadog-api-client-go/

WORKDIR /datadog-api-client-go/
RUN ./get-test-deps.sh

COPY . /datadog-api-client-go

WORKDIR /datadog-api-client-go/datadog_v1
