version: '3'
services:
  test:
    image: datadog-go-integration-test
    build:
      context: .
      dockerfile: Dockerfile.test.v1
    depends_on:
     - datadog
    networks:
      - test
    environment:
      DD_AGENT_HOST: datadog
      DD_TEST_CLIENT_API_KEY: ${DD_TEST_CLIENT_API_KEY}
      DD_TEST_CLIENT_APP_KEY: ${DD_TEST_CLIENT_APP_KEY}
    volumes:
      - ./:/datadog-api-client-go
  datadog:
    image: datadog/agent:latest
    networks:
      - test
    environment:
      DD_API_KEY: ${DD_TEST_CLIENT_API_KEY}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

networks:
  test:
