FROM golang:latest
ENTRYPOINT ["/datadog-api-client-go/run-tests.sh"]

COPY get-test-deps.sh /datadog-api-client-go/

WORKDIR /datadog-api-client-go/
RUN ./get-test-deps.sh

COPY . /datadog-api-client-go

WORKDIR /datadog-api-client-go/api/v1/datadog
