blank_issues_enabled: false
contact_links:
  - name: Datadog Support
    url: https://www.datadoghq.com/support/
    about: Our friendly, knowledgeable support engineers are here to help.
  - name: Datadog Security
    url: https://www.datadoghq.com/security/
    about: We care about security. If you have any questions, or encounter any issues, please contact us.
