/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// WidgetFormulaLimit Options for limiting results returned.
type WidgetFormulaLimit struct {
	// Number of results to return.
	Count *int64          `json:"count,omitempty"`
	Order *QuerySortOrder `json:"order,omitempty"`
	// UnparsedObject contains the raw value of the object if there was an error when deserializing into the struct
	UnparsedObject map[string]interface{} `json:-`
}

// NewWidgetFormulaLimit instantiates a new WidgetFormulaLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWidgetFormulaLimit() *WidgetFormulaLimit {
	this := WidgetFormulaLimit{}
	var order QuerySortOrder = QUERYSORTORDER_DESC
	this.Order = &order
	return &this
}

// NewWidgetFormulaLimitWithDefaults instantiates a new WidgetFormulaLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWidgetFormulaLimitWithDefaults() *WidgetFormulaLimit {
	this := WidgetFormulaLimit{}
	var order QuerySortOrder = QUERYSORTORDER_DESC
	this.Order = &order
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *WidgetFormulaLimit) GetCount() int64 {
	if o == nil || o.Count == nil {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WidgetFormulaLimit) GetCountOk() (*int64, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *WidgetFormulaLimit) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *WidgetFormulaLimit) SetCount(v int64) {
	o.Count = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *WidgetFormulaLimit) GetOrder() QuerySortOrder {
	if o == nil || o.Order == nil {
		var ret QuerySortOrder
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WidgetFormulaLimit) GetOrderOk() (*QuerySortOrder, bool) {
	if o == nil || o.Order == nil {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *WidgetFormulaLimit) HasOrder() bool {
	if o != nil && o.Order != nil {
		return true
	}

	return false
}

// SetOrder gets a reference to the given QuerySortOrder and assigns it to the Order field.
func (o *WidgetFormulaLimit) SetOrder(v QuerySortOrder) {
	o.Order = &v
}

func (o WidgetFormulaLimit) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UnparsedObject != nil {
		return json.Marshal(o.UnparsedObject)
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	if o.Order != nil {
		toSerialize["order"] = o.Order
	}
	return json.Marshal(toSerialize)
}

func (o *WidgetFormulaLimit) UnmarshalJSON(bytes []byte) (err error) {
	raw := map[string]interface{}{}
	all := struct {
		Count *int64          `json:"count,omitempty"`
		Order *QuerySortOrder `json:"order,omitempty"`
	}{}
	err = json.Unmarshal(bytes, &all)
	if err != nil {
		err = json.Unmarshal(bytes, &raw)
		if err != nil {
			return err
		}
		o.UnparsedObject = raw
		return nil
	}
	if v := all.Order; v != nil && !v.IsValid() {
		err = json.Unmarshal(bytes, &raw)
		if err != nil {
			return err
		}
		o.UnparsedObject = raw
		return nil
	}
	o.Count = all.Count
	o.Order = all.Order
	return nil
}

type NullableWidgetFormulaLimit struct {
	value *WidgetFormulaLimit
	isSet bool
}

func (v NullableWidgetFormulaLimit) Get() *WidgetFormulaLimit {
	return v.value
}

func (v *NullableWidgetFormulaLimit) Set(val *WidgetFormulaLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableWidgetFormulaLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableWidgetFormulaLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWidgetFormulaLimit(val *WidgetFormulaLimit) *NullableWidgetFormulaLimit {
	return &NullableWidgetFormulaLimit{value: val, isSet: true}
}

func (v NullableWidgetFormulaLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWidgetFormulaLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
