/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// ApplicationKeyListResponse An application key response.
type ApplicationKeyListResponse struct {
	// Array of application keys.
	ApplicationKeys []ApplicationKey `json:"application_keys,omitempty"`
}
