/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// OrganizationCreateBody Object describing an organization to create.
type OrganizationCreateBody struct {
	Billing OrganizationBilling `json:"billing"`
	// The name of the new child-organization, limited to 32 characters.
	Name string `json:"name"`
	Subscription OrganizationSubscription `json:"subscription"`
}
