/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
	"fmt"
)

// NotebookCreateRequest The description of a notebook create request.
type NotebookCreateRequest struct {
	Data NotebookCreateData `json:"data"`
	// UnparsedObject contains the raw value of the object if there was an error when deserializing into the struct
	UnparsedObject map[string]interface{} `json:-`
}

// NewNotebookCreateRequest instantiates a new NotebookCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotebookCreateRequest(data NotebookCreateData) *NotebookCreateRequest {
	this := NotebookCreateRequest{}
	this.Data = data
	return &this
}

// NewNotebookCreateRequestWithDefaults instantiates a new NotebookCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotebookCreateRequestWithDefaults() *NotebookCreateRequest {
	this := NotebookCreateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *NotebookCreateRequest) GetData() NotebookCreateData {
	if o == nil {
		var ret NotebookCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *NotebookCreateRequest) GetDataOk() (*NotebookCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *NotebookCreateRequest) SetData(v NotebookCreateData) {
	o.Data = v
}

func (o NotebookCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UnparsedObject != nil {
		return json.Marshal(o.UnparsedObject)
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

func (o *NotebookCreateRequest) UnmarshalJSON(bytes []byte) (err error) {
	raw := map[string]interface{}{}
	required := struct {
		Data *NotebookCreateData `json:"data"`
	}{}
	all := struct {
		Data NotebookCreateData `json:"data"`
	}{}
	err = json.Unmarshal(bytes, &required)
	if err != nil {
		return err
	}
	if required.Data == nil {
		return fmt.Errorf("Required field data missing")
	}
	err = json.Unmarshal(bytes, &all)
	if err != nil {
		err = json.Unmarshal(bytes, &raw)
		if err != nil {
			return err
		}
		o.UnparsedObject = raw
		return nil
	}
	o.Data = all.Data
	return nil
}

type NullableNotebookCreateRequest struct {
	value *NotebookCreateRequest
	isSet bool
}

func (v NullableNotebookCreateRequest) Get() *NotebookCreateRequest {
	return v.value
}

func (v *NullableNotebookCreateRequest) Set(val *NotebookCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNotebookCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNotebookCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotebookCreateRequest(val *NotebookCreateRequest) *NullableNotebookCreateRequest {
	return &NullableNotebookCreateRequest{value: val, isSet: true}
}

func (v NullableNotebookCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotebookCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
