/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// WidgetImageSizing How to size the image on the widget.
type WidgetImageSizing string

// List of WidgetImageSizing
const (
	ZOOM WidgetImageSizing = "zoom"
	FIT WidgetImageSizing = "fit"
	CENTER WidgetImageSizing = "center"
)
