/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
import (
	"time"
)
// UsageSnmpHour The number of SNMP devices for each hour for a given organization.
type UsageSnmpHour struct {
	// The hour for the usage.
	Hour time.Time `json:"hour,omitempty"`
	// Contains the number of SNMP devices.
	SnmpDevices int64 `json:"snmp_devices,omitempty"`
}
