/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"bytes"
	"encoding/json"
)

// MonitorType The type of the monitor
type MonitorType string

// List of MonitorType
const (
	MONITORTYPE_COMPOSITE             MonitorType = "composite"
	MONITORTYPE_EVENT_ALERT           MonitorType = "event alert"
	MONITORTYPE_LOG_ALERT             MonitorType = "log alert"
	MONITORTYPE_METRIC_ALERT          MonitorType = "metric alert"
	MONITORTYPE_PROCESS_ALERT         MonitorType = "process alert"
	MONITORTYPE_QUERY_ALERT           MonitorType = "query alert"
	MONITORTYPE_SERVICE_CHECK         MonitorType = "service check"
	MONITORTYPE_SYNTHETICS_ALERT      MonitorType = "synthetics alert"
	MONITORTYPE_TRACE_ANALYTICS_ALERT MonitorType = "trace-analytics alert"
)

// Ptr returns reference to MonitorType value
func (v MonitorType) Ptr() *MonitorType {
	return &v
}

type NullableMonitorType struct {
	Value        MonitorType
	ExplicitNull bool
}

func (v NullableMonitorType) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableMonitorType) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
