/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// SloHistoryMetricsSeries A representation of `metric` based SLO time series for the provided queries. This is the same response type from `batch_query` endpoint.
type SloHistoryMetricsSeries struct {
	// Count of submitted metrics.
	Count int64 `json:"count"`
	Metadata SloHistoryMetricsSeriesMetadata `json:"metadata"`
	// Total sum of the query.
	Sum float64 `json:"sum"`
	// The query values for each metric.
	Values []float64 `json:"values"`
}
