/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// EventResponse Object containing an event response.
type EventResponse struct {
	Event Event `json:"event,omitempty"`
	// A status.
	Status string `json:"status,omitempty"`
}
