/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// LogsUserAgentParserType Type of logs User-Agent parser.
type LogsUserAgentParserType string

// List of LogsUserAgentParserType
const (
	USER_AGENT_PARSER LogsUserAgentParserType = "user-agent-parser"
)
