/*
 * (C) Datadog, Inc. 2019
 * All rights reserved
 * Licensed under a 3-clause BSD style license (see LICENSE)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"bytes"
	"encoding/json"
)

// MonitorOverallStates the model 'MonitorOverallStates'
type MonitorOverallStates string

// List of MonitorOverallStates
const (
	MONITOROVERALLSTATES_ALERT   MonitorOverallStates = "Alert"
	MONITOROVERALLSTATES_IGNORED MonitorOverallStates = "Ignored"
	MONITOROVERALLSTATES_NO_DATA MonitorOverallStates = "No Data"
	MONITOROVERALLSTATES_OK      MonitorOverallStates = "OK"
	MONITOROVERALLSTATES_SKIPPED MonitorOverallStates = "Skipped"
	MONITOROVERALLSTATES_UNKNOWN MonitorOverallStates = "Unknown"
	MONITOROVERALLSTATES_WARN    MonitorOverallStates = "Warn"
)

type NullableMonitorOverallStates struct {
	Value        MonitorOverallStates
	ExplicitNull bool
}

func (v NullableMonitorOverallStates) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableMonitorOverallStates) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
