/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// WidgetCompareTo Timeframe used for the change comparison.
type WidgetCompareTo string

// List of WidgetCompareTo
const (
	HOUR_BEFORE WidgetCompareTo = "hour_before"
	DAY_BEFORE WidgetCompareTo = "day_before"
	WEEK_BEFORE WidgetCompareTo = "week_before"
	MONTH_BEFORE WidgetCompareTo = "month_before"
)
