/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// SloTimeframe The SLO time window options.
type SloTimeframe string

// List of SLOTimeframe
const (
	SEVEN_DAYS SloTimeframe = "7d"
	THIRTY_DAYS SloTimeframe = "30d"
	NINETY_DAYS SloTimeframe = "90d"
)
