/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// LogsListRequest Object to send with the request to retrieve a list of logs from your Organization.
type LogsListRequest struct {
	// For multi-index organizations, the log index in which the request is performed. Default to '*' (all indexes).
	Index string `json:"index,omitempty"`
	// Number of logs return in the response.
	Limit int32 `json:"limit,omitempty"`
	// The search query - following the log search syntax.
	Query string `json:"query"`
	Sort LogsSort `json:"sort,omitempty"`
	// Hash identifier of the first log to return in the list, available in a log `id` attribute. This parameter is used for the pagination feature.  **Note**: This parameter is ignored if the corresponding log is out of the scope of the specified time window.
	StartAt string `json:"startAt,omitempty"`
	Time LogsListRequestTime `json:"time"`
}
