/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"bytes"
	"encoding/json"
	"time"
)

// UsageFargateHour struct for UsageFargateHour
type UsageFargateHour struct {
	// The hour for the usage.
	Hour *time.Time `json:"hour,omitempty"`
	// Contains the number of Fargate tasks run.
	TasksCount *int64 `json:"tasks_count,omitempty"`
}

// GetHour returns the Hour field value if set, zero value otherwise.
func (o *UsageFargateHour) GetHour() time.Time {
	if o == nil || o.Hour == nil {
		var ret time.Time
		return ret
	}
	return *o.Hour
}

// GetHourOk returns a tuple with the Hour field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *UsageFargateHour) GetHourOk() (time.Time, bool) {
	if o == nil || o.Hour == nil {
		var ret time.Time
		return ret, false
	}
	return *o.Hour, true
}

// HasHour returns a boolean if a field has been set.
func (o *UsageFargateHour) HasHour() bool {
	if o != nil && o.Hour != nil {
		return true
	}

	return false
}

// SetHour gets a reference to the given time.Time and assigns it to the Hour field.
func (o *UsageFargateHour) SetHour(v time.Time) {
	o.Hour = &v
}

// GetTasksCount returns the TasksCount field value if set, zero value otherwise.
func (o *UsageFargateHour) GetTasksCount() int64 {
	if o == nil || o.TasksCount == nil {
		var ret int64
		return ret
	}
	return *o.TasksCount
}

// GetTasksCountOk returns a tuple with the TasksCount field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *UsageFargateHour) GetTasksCountOk() (int64, bool) {
	if o == nil || o.TasksCount == nil {
		var ret int64
		return ret, false
	}
	return *o.TasksCount, true
}

// HasTasksCount returns a boolean if a field has been set.
func (o *UsageFargateHour) HasTasksCount() bool {
	if o != nil && o.TasksCount != nil {
		return true
	}

	return false
}

// SetTasksCount gets a reference to the given int64 and assigns it to the TasksCount field.
func (o *UsageFargateHour) SetTasksCount(v int64) {
	o.TasksCount = &v
}

type NullableUsageFargateHour struct {
	Value        UsageFargateHour
	ExplicitNull bool
}

func (v NullableUsageFargateHour) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableUsageFargateHour) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
