/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// MetricsListResponse Object listing all metric names stored by Datadog since a given time.
type MetricsListResponse struct {
	// Time when the metrics were active, seconds since the Unix epoch.
	From string `json:"from,omitempty"`
	// List of metric names.
	Metrics []string `json:"metrics,omitempty"`
}
