/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"bytes"
	"encoding/json"
)

// Error404 struct for Error404
type Error404 struct {
	Errors []string `json:"errors"`
}

// NewError404 instantiates a new Error404 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewError404(errors []string) *Error404 {
	this := Error404{}
	this.Errors = errors
	return &this
}

// NewError404WithDefaults instantiates a new Error404 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewError404WithDefaults() *Error404 {
	this := Error404{}
	return &this
}

// GetErrors returns the Errors field value
func (o *Error404) GetErrors() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Errors
}

// SetErrors sets field value
func (o *Error404) SetErrors(v []string) {
	o.Errors = v
}

type NullableError404 struct {
	Value        Error404
	ExplicitNull bool
}

func (v NullableError404) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableError404) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
