/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// QueryValueWidgetDefinition Query values display the current value of a given metric, APM, or log query.
type QueryValueWidgetDefinition struct {
	// Whether to use auto-scaling or not.
	Autoscale bool `json:"autoscale,omitempty"`
	// Display a unit of your choice on the widget.
	CustomUnit string `json:"custom_unit,omitempty"`
	// Number of decimals to show. If not defined, the widget uses the raw value.
	Precision int64 `json:"precision,omitempty"`
	// Widget definition.
	Requests []QueryValueWidgetRequest `json:"requests"`
	TextAlign WidgetTextAlign `json:"text_align,omitempty"`
	Time WidgetTime `json:"time,omitempty"`
	// Title of your widget.
	Title string `json:"title,omitempty"`
	TitleAlign WidgetTextAlign `json:"title_align,omitempty"`
	// Size of the title.
	TitleSize string `json:"title_size,omitempty"`
	Type QueryValueWidgetDefinitionType `json:"type"`
}
