/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// ApplicationKey An application key with its associated metadata.
type ApplicationKey struct {
	// Hash of an application key.
	Hash string `json:"hash,omitempty"`
	// Name of an application key.
	Name string `json:"name,omitempty"`
	// Owner of an application key.
	Owner string `json:"owner,omitempty"`
}
