/*
 * Datadog API Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog
// WidgetMessageDisplay Amount of log lines to display
type WidgetMessageDisplay string

// List of WidgetMessageDisplay
const (
	INLINE WidgetMessageDisplay = "inline"
	EXPANDED_MEDIUM WidgetMessageDisplay = "expanded-md"
	EXPANDED_LARGE WidgetMessageDisplay = "expanded-lg"
)
