# Allows the scheduled cache builder in ddoghq/datadog-api-spec to read this repository.
issuer: https://token.actions.githubusercontent.com

subject: repo:ddoghq/datadog-api-spec:ref:refs/heads/master

claim_pattern:
  event_name: schedule
  job_workflow_ref: ddoghq/datadog-api-spec/\.github/workflows/cache-builder\.yml@refs/heads/master
  ref: refs/heads/master
  repository: ddoghq/datadog-api-spec

permissions:
  contents: read

