// Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2019-Present Datadog, Inc.

package datadogV2

import (
	"encoding/json"
	"fmt"
)

// DashboardReportScheduleRepeatAt ISO8601 formatted time (HH:MM) to send the report, using the time zone specified in the `timezone` field.
type DashboardReportScheduleRepeatAt string

// List of DashboardReportScheduleRepeatAt.
const (
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_00_00 DashboardReportScheduleRepeatAt = "00:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_00_30 DashboardReportScheduleRepeatAt = "00:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_01_00 DashboardReportScheduleRepeatAt = "01:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_01_30 DashboardReportScheduleRepeatAt = "01:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_02_00 DashboardReportScheduleRepeatAt = "02:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_02_30 DashboardReportScheduleRepeatAt = "02:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_03_00 DashboardReportScheduleRepeatAt = "03:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_03_30 DashboardReportScheduleRepeatAt = "03:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_04_00 DashboardReportScheduleRepeatAt = "04:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_04_30 DashboardReportScheduleRepeatAt = "04:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_05_00 DashboardReportScheduleRepeatAt = "05:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_05_30 DashboardReportScheduleRepeatAt = "05:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_06_00 DashboardReportScheduleRepeatAt = "06:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_06_30 DashboardReportScheduleRepeatAt = "06:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_07_00 DashboardReportScheduleRepeatAt = "07:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_07_30 DashboardReportScheduleRepeatAt = "07:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_08_00 DashboardReportScheduleRepeatAt = "08:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_08_30 DashboardReportScheduleRepeatAt = "08:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_09_00 DashboardReportScheduleRepeatAt = "09:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_09_30 DashboardReportScheduleRepeatAt = "09:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_10_00 DashboardReportScheduleRepeatAt = "10:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_10_30 DashboardReportScheduleRepeatAt = "10:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_11_00 DashboardReportScheduleRepeatAt = "11:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_11_30 DashboardReportScheduleRepeatAt = "11:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_12_00 DashboardReportScheduleRepeatAt = "12:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_12_30 DashboardReportScheduleRepeatAt = "12:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_13_00 DashboardReportScheduleRepeatAt = "13:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_13_30 DashboardReportScheduleRepeatAt = "13:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_14_00 DashboardReportScheduleRepeatAt = "14:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_14_30 DashboardReportScheduleRepeatAt = "14:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_15_00 DashboardReportScheduleRepeatAt = "15:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_15_30 DashboardReportScheduleRepeatAt = "15:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_16_00 DashboardReportScheduleRepeatAt = "16:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_16_30 DashboardReportScheduleRepeatAt = "16:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_17_00 DashboardReportScheduleRepeatAt = "17:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_17_30 DashboardReportScheduleRepeatAt = "17:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_18_00 DashboardReportScheduleRepeatAt = "18:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_18_30 DashboardReportScheduleRepeatAt = "18:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_19_00 DashboardReportScheduleRepeatAt = "19:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_19_30 DashboardReportScheduleRepeatAt = "19:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_20_00 DashboardReportScheduleRepeatAt = "20:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_20_30 DashboardReportScheduleRepeatAt = "20:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_21_00 DashboardReportScheduleRepeatAt = "21:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_21_30 DashboardReportScheduleRepeatAt = "21:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_22_00 DashboardReportScheduleRepeatAt = "22:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_22_30 DashboardReportScheduleRepeatAt = "22:30"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_23_00 DashboardReportScheduleRepeatAt = "23:00"
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_23_30 DashboardReportScheduleRepeatAt = "23:30"
)

var allowedDashboardReportScheduleRepeatAtEnumValues = []DashboardReportScheduleRepeatAt{
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_00_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_00_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_01_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_01_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_02_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_02_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_03_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_03_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_04_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_04_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_05_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_05_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_06_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_06_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_07_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_07_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_08_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_08_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_09_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_09_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_10_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_10_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_11_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_11_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_12_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_12_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_13_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_13_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_14_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_14_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_15_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_15_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_16_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_16_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_17_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_17_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_18_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_18_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_19_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_19_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_20_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_20_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_21_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_21_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_22_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_22_30,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_23_00,
	DASHBOARDREPORTSCHEDULEREPEATAT_DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_23_30,
}

// GetAllowedValues reeturns the list of possible values.
func (v *DashboardReportScheduleRepeatAt) GetAllowedValues() []DashboardReportScheduleRepeatAt {
	return allowedDashboardReportScheduleRepeatAtEnumValues
}

// UnmarshalJSON deserializes the given payload.
func (v *DashboardReportScheduleRepeatAt) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	*v = DashboardReportScheduleRepeatAt(value)
	return nil
}

// NewDashboardReportScheduleRepeatAtFromValue returns a pointer to a valid DashboardReportScheduleRepeatAt
// for the value passed as argument, or an error if the value passed is not allowed by the enum.
func NewDashboardReportScheduleRepeatAtFromValue(v string) (*DashboardReportScheduleRepeatAt, error) {
	ev := DashboardReportScheduleRepeatAt(v)
	if ev.IsValid() {
		return &ev, nil
	}
	return nil, fmt.Errorf("invalid value '%v' for DashboardReportScheduleRepeatAt: valid values are %v", v, allowedDashboardReportScheduleRepeatAtEnumValues)
}

// IsValid return true if the value is valid for the enum, false otherwise.
func (v DashboardReportScheduleRepeatAt) IsValid() bool {
	for _, existing := range allowedDashboardReportScheduleRepeatAtEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DashboardReportScheduleRepeatAt value.
func (v DashboardReportScheduleRepeatAt) Ptr() *DashboardReportScheduleRepeatAt {
	return &v
}

// NullableDashboardReportScheduleRepeatAt handles when a null is used for DashboardReportScheduleRepeatAt.
type NullableDashboardReportScheduleRepeatAt struct {
	value *DashboardReportScheduleRepeatAt
	isSet bool
}

// Get returns the associated value.
func (v NullableDashboardReportScheduleRepeatAt) Get() *DashboardReportScheduleRepeatAt {
	return v.value
}

// Set changes the value and indicates it's been called.
func (v *NullableDashboardReportScheduleRepeatAt) Set(val *DashboardReportScheduleRepeatAt) {
	v.value = val
	v.isSet = true
}

// IsSet returns whether Set has been called.
func (v NullableDashboardReportScheduleRepeatAt) IsSet() bool {
	return v.isSet
}

// Unset sets the value to nil and resets the set flag.
func (v *NullableDashboardReportScheduleRepeatAt) Unset() {
	v.value = nil
	v.isSet = false
}

// NewNullableDashboardReportScheduleRepeatAt initializes the struct as if Set has been called.
func NewNullableDashboardReportScheduleRepeatAt(val *DashboardReportScheduleRepeatAt) *NullableDashboardReportScheduleRepeatAt {
	return &NullableDashboardReportScheduleRepeatAt{value: val, isSet: true}
}

// MarshalJSON serializes the associated value.
func (v NullableDashboardReportScheduleRepeatAt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// UnmarshalJSON deserializes the payload and sets the flag as if Set has been called.
func (v *NullableDashboardReportScheduleRepeatAt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
