name: Reusable Examples Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''

jobs:
  examples:
    runs-on: ubuntu-latest
    if: >
      (github.event.pull_request.draft == false &&
       !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
       !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/')) ||
      github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: DataDog/datadog-api-client-go
          ref: ${{ inputs.target-branch || github.ref }}
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
          cache: true
          cache-dependency-path: tests/go.sum
      - name: Check examples
        run: ./check-examples.sh
        shell: bash