name: Reusable Complete CI Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      
    secrets:
      PIPELINE_GITHUB_APP_ID:
        required: false
      PIPELINE_GITHUB_APP_PRIVATE_KEY:
        required: false
      # Integration test secrets
      DD_API_KEY:
        required: false
      DD_CLIENT_API_KEY:
        required: false
      DD_CLIENT_APP_KEY:
        required: false
      SLEEP_AFTER_REQUEST:
        required: false

jobs:
  pre-commit:
    uses: ./.github/workflows/reusable-pre-commit.yml
    with:
      target-branch: ${{ inputs.target-branch }}
      enable-commit-changes: false  # Don't auto-commit in external CI
    secrets:
      PIPELINE_GITHUB_APP_ID: ${{ secrets.PIPELINE_GITHUB_APP_ID }}
      PIPELINE_GITHUB_APP_PRIVATE_KEY: ${{ secrets.PIPELINE_GITHUB_APP_PRIVATE_KEY }}

  test:
    uses: ./.github/workflows/reusable-go-test.yml
    with:
      target-branch: ${{ inputs.target-branch }}

  examples:
    uses: ./.github/workflows/reusable-examples.yml
    with:
      target-branch: ${{ inputs.target-branch }}

  integration:
    uses: ./.github/workflows/reusable-integration-test.yml
    with:
      target-branch: ${{ inputs.target-branch }}
    secrets:
      PIPELINE_GITHUB_APP_ID: ${{ secrets.PIPELINE_GITHUB_APP_ID }}
      PIPELINE_GITHUB_APP_PRIVATE_KEY: ${{ secrets.PIPELINE_GITHUB_APP_PRIVATE_KEY }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_CLIENT_API_KEY: ${{ secrets.DD_CLIENT_API_KEY }}
      DD_CLIENT_APP_KEY: ${{ secrets.DD_CLIENT_APP_KEY }}
      SLEEP_AFTER_REQUEST: ${{ secrets.SLEEP_AFTER_REQUEST }}

