name: Run Integration Tests

on:
  pull_request:
    branches:
      - master
    types: ["opened", "reopened", "ready_for_review", "labeled", "synchronize"]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
      !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/') &&
      contains(github.event.pull_request.labels.*.name, 'ci/integrations')
    services:
      datadog-agent:
        image: datadog/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_HOSTNAME: "none"
          DD_INSIDE_CI: "true"
    env:
      APIGENTOOLS_LANG: go
      APIGENTOOLS_VERBOSE: true
    steps:
    - name: Run integration tests
      shell: bash
      run: ./run-test.sh
      env:
        CI: "true"
        DD_AGENT_HOST: datadog-agent
        DD_ENV: prod
        DD_SERVICE: datadog-api-client-go
        DD_TAGS: "team:integration-tools-and-libraries"
        DD_TEST_CLIENT_API_KEY: ${{ secrets.DD_CLIENT_API_KEY }}
        DD_TEST_CLIENT_APP_KEY: ${{ secrets.DD_CLIENT_APP_KEY }}
        RECORD: "none"
