name: Run Tests

permissions:
  contents: read

env:
  GIT_AUTHOR_EMAIL: "packages@datadoghq.com"
  GIT_AUTHOR_NAME: "ci.datadog-api-spec"

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"

concurrency:
  group: unit-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  call-reusable-workflow:
    if: >
      (github.event.pull_request.draft == false &&
       !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
       !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/')) ||
      github.event_name == 'schedule'
    uses: ./.github/workflows/reusable-go-test.yml
    with:
      go-versions: '["1.22.x", "1.23.x"]'
      go-build-tags: '["--tags=goccy_gojson", ""]'
      platforms: '["ubuntu-latest"]'
      cache-dependency-path: 'tests/go.sum'
      enable-status-reporting: true
      status-context: 'master/unit'
    secrets:
      PIPELINE_GITHUB_APP_ID: ${{ secrets.PIPELINE_GITHUB_APP_ID }}
      PIPELINE_GITHUB_APP_PRIVATE_KEY: ${{ secrets.PIPELINE_GITHUB_APP_PRIVATE_KEY }}
